name: Running Integration test

on: [push, pull_request]


jobs:
  container-job:
    runs-on: ubuntu-latest
    services:
      postgres_db:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: jetbrains_academy
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - uses: actions/checkout@v1

      - name: populate database schema
        run: |
          psql -h localhost -U postgres -d jetbrains_academy 'CREATE SCHEMA auth'

      - name: Set up java 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Run tests
        run: mvn test